---
# tasks file for bareos_repository

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Add repository (rpm)
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: true
    gpgkey: "{{ item.gpgkey }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
  no_log: true
  loop: "{{ bareos_repository_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - ansible_pkg_mgr in [ "dnf", "yum" ] or
      ansible_facts.os_family == "RedHat"

- name: Run tasks on apt based distributions
  when:
    - ansible_pkg_mgr in [ "apt" ]
  block:
    - name: Install dependencies for apt
      ansible.builtin.package:
        name:
          - ca-certificates
          - gpg

    - name: Download gpg key (apt)
      ansible.builtin.get_url:
        url: "{{ bareos_repository_gpg_key }}"
        dest: /etc/apt/bareos.gpg
        username: "{{ bareos_repository_username }}"
        password: "{{ bareos_repository_password }}"
        owner: root
        group: root
        mode: "0644"
      no_log: true

    - name: Place credentials file (apt)
      ansible.builtin.copy:
        content: |
          machine download.bareos.com
          login {{ bareos_repository_username }}
          password {{ bareos_repository_password }}
        dest: /etc/apt/auth.conf.d/download_bareos_com.conf
        owner: root
        group: root
        mode: "0600"
      no_log: true
      when:
        - bareos_repository_type == "subscription"

    - name: Add repository (apt)
      ansible.builtin.apt_repository:
        repo: "{{ item.deb_repo }}"
        state: present
        filename: "{{ item.name }}"
        update_cache: true
      no_log: true
      loop: "{{ bareos_repository_list }}"
      loop_control:
        label: "{{ item.name }}"

- name: Run tasks on zypper based distributions
  when:
    - ansible_pkg_mgr in [ "zypper" ]
  block:
    - name: Download gpg key (zypper)
      ansible.builtin.get_url:
        url: "{{ bareos_repository_gpg_key }}"
        dest: /etc/gnupg/bareos.gpg
        username: "{{ bareos_repository_username }}"
        password: "{{ bareos_repository_password }}"
        owner: root
        group: root
        mode: "0644"
      no_log: true

    - name: Import gpg key (zypper)
      ansible.builtin.rpm_key:
        key: /etc/gnupg/bareos.gpg

    - name: Place credentials file (zypper)
      ansible.builtin.copy:
        content: |
          username={{ bareos_repository_username }}
          password={{ bareos_repository_password }}
        dest: /etc/zypp/credentials.d/bareos
        owner: root
        group: root
        mode: "0600"
      no_log: true
      when:
        - bareos_repository_type == "subscription"

    - name: Add repository (zypper)
      community.general.zypper_repository:
        name: "{{ item.name }}"
        repo: "{{ item.repo }}"
        state: present
      loop: "{{ bareos_repository_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - bareos_repository_type != "subscription"

    - name: Add repository (zypper) (subscription)
      community.general.zypper_repository:
        name: "{{ item.name }}"
        # credential file needs to be appended to URL
        repo: "{{ item.repo }}?credentials=bareos"
        autorefresh: false  # avoid credential issues running zypper as non-root
        state: present
      loop: "{{ bareos_repository_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - bareos_repository_type == "subscription"

- name: Run tasks on FreeBSD distributions
  when:
    - ansible_os_family == "FreeBSD"
  block:
    - name: Make sure repo directory is present
      ansible.builtin.file:
        path: /usr/local/etc/pkg/repos
        state: directory
        owner: root
        group: wheel
        mode: "0755"

    - name: Add PKG repository file
      ansible.builtin.template:
        src: FreeBSD_repo.j2
        dest: /usr/local/etc/pkg/repos/bareos.conf
        owner: root
        group: wheel
        mode: "0640"
      no_log: true
      notify:
        - FreeBSD PKG reload

- name: Enable tracebacks
  when:
    - bareos_repository_enable_tracebacks
  block:
    - name: Add debuginfo repository (rpm)
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgcheck: true
        gpgkey: "{{ item.gpgkey }}"
        username: "{{ item.username | default(omit) }}"
        password: "{{ item.password | default(omit) }}"
      no_log: true
      loop: "{{ bareos_repository_debug_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - ansible_pkg_mgr in [ "dnf", "yum" ]

    - name: Add repository (zypper)
      community.general.zypper_repository:
        name: "{{ item.name }}"
        repo: "{{ item.repo }}"
        state: present
      loop: "{{ bareos_repository_debug_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - ansible_pkg_mgr in [ "zypper" ]

    - name: Install required packages
      ansible.builtin.package:
        name: "{{ bareos_repository_debug_required_packages }}"
