---
# tasks file for bareos_repository

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Add repository (rpm)
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: true
    gpgkey: "{{ item.gpgkey }}"
    username: "{{ item.username | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
  no_log: true
  loop: "{{ bareos_repository_list }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - ansible_pkg_mgr in [ "dnf", "yum" ] or
      ansible_facts.os_family == "RedHat"

- name: Run tasks on apt based distributions
  when:
    - ansible_pkg_mgr in [ "apt" ]
  block:
    - name: Install dependencies for apt
      ansible.builtin.package:
        name:
          - ca-certificates
          - gpg
          - python3-debian

    # has to be downloaded first as key for subscription repo is behind basic-auth,
    # which is not supported by builtin.apt_repository/builtin_deb822_repository
    - name: Download gpg key (apt)
      ansible.builtin.get_url:
        url: "{{ bareos_repository_gpg_key }}"
        dest: /etc/apt/keyrings/bareos.gpg
        username: "{{ bareos_repository_username }}"
        password: "{{ bareos_repository_password }}"
        force: true  # required so file is replaced if upstream key changes
        owner: root
        group: root
        mode: "0644"
      no_log: true
      changed_when: false  # avoid reporting a change due to force: true

    - name: Place credentials file (apt)
      ansible.builtin.copy:
        content: |
          machine download.bareos.com
          login {{ bareos_repository_username }}
          password {{ bareos_repository_password }}
        dest: /etc/apt/auth.conf.d/download_bareos_com.conf
        force: true
        owner: root
        group: root
        mode: "0600"
      no_log: true
      when:
        - bareos_repository_type == "subscription"

    # don't use apt_repository module as it cannot handle version changes in URL
    # see: https://github.com/adfinis/ansible-role-bareos_repository/pull/30#issue-3875677300
    - name: Add repository (apt)
      ansible.builtin.template:
        src: apt_repo.j2
        dest: "/etc/apt/sources.list.d/{{ item.name }}.list"
        owner: root
        group: root
        mode: "0644"
      loop: "{{ bareos_repository_list }}"
      loop_control:
        label: "{{ item.name }}"
      notify:
        - Apt update cache
      when:
        - (ansible_facts.distribution == "Debian" and ansible_facts.distribution_major_version | int <= 12) or
          (ansible_facts.distribution == "Ubuntu" and ansible_facts.distribution_major_version | int <= 22) or
          (ansible_facts.distribution == "Univention Corporate Server" and ansible_distribution_version is version("5.2", "<"))

    - name: Add repository (apt) deb822 format and remove old format
      when:
        - (ansible_facts.distribution == "Debian" and ansible_facts.distribution_major_version | int >= 13) or
          (ansible_facts.distribution == "Ubuntu" and ansible_facts.distribution_major_version | int >= 24) or
          (ansible_facts.distribution == "Univention Corporate Server" and ansible_distribution_version is version("5.2", ">="))

      block:

        # use file rather than apt_repository module, to avoid possible issues during repo version changes,
        # as item.deb_repo contains current version of bareos_repository_version and
        # repo file(s) with older version are ignored and not cleaned-up properly.
        - name: Remove repository in old format
          ansible.builtin.file:
            path: "/etc/apt/sources.list.d/{{ item.name }}.list"
            state: absent
          loop: "{{ bareos_repository_list }}"
          loop_control:
            label: "{{ item.name }}"
          notify:
            - Apt update cache

        - name: Add repository (apt) deb822 format
          ansible.builtin.deb822_repository:
            name: "{{ item.name }}"
            uris: "{{ item.repo }}"
            enabled: true
            types:
              - deb
              - deb-src
            suites: /
            signed_by: /etc/apt/keyrings/bareos.gpg
          loop: "{{ bareos_repository_list }}"
          loop_control:
            label: "{{ item.name }}"
          notify:
            - Apt update cache

- name: Run tasks on zypper based distributions
  when:
    - ansible_pkg_mgr in [ "zypper" ]
  block:
    - name: Download gpg key (zypper)
      ansible.builtin.get_url:
        url: "{{ bareos_repository_gpg_key }}"
        dest: /etc/gnupg/bareos.gpg
        username: "{{ bareos_repository_username }}"
        password: "{{ bareos_repository_password }}"
        owner: root
        group: root
        mode: "0644"
      no_log: true

    - name: Import gpg key (zypper)
      ansible.builtin.rpm_key:
        key: /etc/gnupg/bareos.gpg

    - name: Place credentials file (zypper)
      ansible.builtin.copy:
        content: |
          username={{ bareos_repository_username }}
          password={{ bareos_repository_password }}
        dest: /etc/zypp/credentials.d/bareos
        owner: root
        group: root
        mode: "0600"
      no_log: true
      when:
        - bareos_repository_type == "subscription"

    - name: Add repository (zypper)
      community.general.zypper_repository:
        name: "{{ item.name }}"
        repo: "{{ item.repo }}"
        state: present
      loop: "{{ bareos_repository_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - bareos_repository_type != "subscription"

    - name: Add repository (zypper) (subscription)
      community.general.zypper_repository:
        name: "{{ item.name }}"
        # credential file needs to be appended to URL
        repo: "{{ item.repo }}?credentials=bareos"
        autorefresh: false  # avoid credential issues running zypper as non-root
        state: present
      loop: "{{ bareos_repository_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - bareos_repository_type == "subscription"

- name: Run tasks on FreeBSD distributions
  when:
    - ansible_os_family == "FreeBSD"
  block:
    - name: Make sure repo directory is present
      ansible.builtin.file:
        path: /usr/local/etc/pkg/repos
        state: directory
        owner: root
        group: wheel
        mode: "0755"

    - name: Add PKG repository file
      ansible.builtin.template:
        src: FreeBSD_repo.j2
        dest: /usr/local/etc/pkg/repos/bareos.conf
        owner: root
        group: wheel
        mode: "0640"
      no_log: true
      notify:
        - FreeBSD PKG reload

- name: Enable tracebacks
  when:
    - bareos_repository_enable_tracebacks
  block:
    - name: Add debuginfo repository (rpm)
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgcheck: true
        gpgkey: "{{ item.gpgkey }}"
        username: "{{ item.username | default(omit) }}"
        password: "{{ item.password | default(omit) }}"
      no_log: true
      loop: "{{ bareos_repository_debug_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - ansible_pkg_mgr in [ "dnf", "yum" ]

    - name: Add repository (zypper)
      community.general.zypper_repository:
        name: "{{ item.name }}"
        repo: "{{ item.repo }}"
        state: present
      loop: "{{ bareos_repository_debug_list }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - ansible_pkg_mgr in [ "zypper" ]

    - name: Install required packages
      ansible.builtin.package:
        name: "{{ bareos_repository_debug_required_packages }}"
